project_id = "ykgawuawtfpghshuwmde"

[functions.redirect]
verify_jwt = false

[functions.webhook]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
